/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import { Provider } from 'nuxt-yapi/provider'
import type { paths } from './schema'

export class Yapi extends Provider {
  get ft() {
    return this.fetcher<paths>()
  }

  get userBotLoginPost() {
    return this.ft.path('/user/bot:login').method('post').create()!
  }

  get userUser() {
    return this.ft.path('/user/user').method('get').create()!
  }

  get userCheck() {
    return this.ft.path('/user/check').method('get').create()!
  }

  get userUserLevel() {
    return this.ft.path('/user/user-level').method('get').create()!
  }

  get userUserLoginPost() {
    return this.ft.path('/user/user:login').method('post').create()!
  }

  get userMsgToLogin() {
    return this.ft.path('/user/msg-to-login').method('get').create()!
  }

  get userInvitationRelations() {
    return this.ft.path('/user/invitation-relations').method('get').create()!
  }

  get userInvitationRelation() {
    return this.ft.path('/user/invitation-relation').method('get').create()!
  }

  get botInviterRebates() {
    return this.ft.path('/bot/inviter-rebates').method('get').create()!
  }

  get userInviterRebates() {
    return this.ft.path('/user/inviter-rebates').method('get').create()!
  }

  get userInviteStakeRebates() {
    return this.ft.path('/user/invite-stake-rebates').method('get').create()!
  }

  get userRebateWithdrawRecords() {
    return this.ft.path('/user/rebate-withdraw-records').method('get').create()!
  }

  get userRebateWithdrawRecord() {
    return this.ft.path('/user/rebate-withdraw-record').method('get').create()!
  }

  get userRebateWithdrawPost() {
    return this.ft.path('/user/rebate:withdraw').method('post').create()!
  }

  get blockchainTradeHistory() {
    return this.ft.path('/blockchain/trade-history').method('get').create()!
  }

  get blockchainPairs() {
    return this.ft.path('/blockchain/pairs').method('get').create()!
  }

  get blockchainUserOrders() {
    return this.ft.path('/blockchain/user-orders').method('get').create()!
  }

  get blockchainOrderBooks() {
    return this.ft.path('/blockchain/order-books').method('get').create()!
  }

  get blockchainCheckOrder() {
    return this.ft.path('/blockchain/check-order').method('get').create()!
  }

  get blockchainTradeStatistic() {
    return this.ft.path('/blockchain/trade-statistic').method('get').create()!
  }

  get blockchainTradeHistoryDetail() {
    return this.ft.path('/blockchain/trade-history-detail').method('get').create()!
  }

  get userDevices() {
    return this.ft.path('/user/devices').method('get').create()!
  }

  get userCrowdfundingDevices() {
    return this.ft.path('/user/crowdfunding-devices').method('get').create()!
  }

  get userVoteDevices() {
    return this.ft.path('/user/vote-devices').method('get').create()!
  }

  get powerSingleClaimPost() {
    return this.ft.path('/power/single/claim').method('post').create()!
  }

  get powerSingle() {
    return this.ft.path('/power/single').method('get').create()!
  }

  get powerWithdrawPost() {
    return this.ft.path('/power/withdraw').method('post').create()!
  }

  get powerList() {
    return this.ft.path('/power/list').method('get').create()!
  }

  get powerSingleCheck() {
    return this.ft.path('/power/single/check').method('get').create()!
  }

  get rebateComputePost() {
    return this.ft.path('/rebate/compute').method('post').create()!
  }

  get userDailyRewardInfoCpPost() {
    return this.ft.path('/user/daily-reward-info-cp').method('post').create()!
  }

  get userAirdropRecord() {
    return this.ft.path('/user/airdrop-record').method('get').create()!
  }

  get userAirdropRecordPut() {
    return this.ft.path('/user/airdrop-record').method('put').create()!
  }

  get userAirdropRecordPost() {
    return this.ft.path('/user/airdrop-record').method('post').create()!
  }

  get userAirdropRecordDelete() {
    return this.ft.path('/user/airdrop-record').method('delete').create()!
  }

  get userAirdropRecords() {
    return this.ft.path('/user/airdrop-records').method('get').create()!
  }
}
